[project]
name = "ai-dev1-2026projectscinema-city"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hagay Onn the spot", email = "eladm1947@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-dev1-2026projectscinema-city = "ai_dev1_2026projectscinema_city:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
